/**
* @api {get} /api/appclients/:id 2. Get only one AppClient
* @apiVersion 1.0.0
* @apiName GetOneAppClient
* @apiGroup AppClients
* @apiPermission TokenAccess
*
* @apiDescription AppClients who have a token and can access resources.
*
* @apiParam (Param) {Number} id ID of the AppClient.
*
* @apiSuccess {Number} Id       AppClient ID on database.
* @apiSuccess {String} token       Token that give access to resources.
* @apiSuccess {String} description       Defines the AppClient.
* @apiSuccess {Date} createdAt       Creation date generated by Sequelize.
* @apiSuccess {Date} updatedAt       Last update of this AppClient.
* @apiSuccess {Date} deletedAt       Null if appClient is not deleted or removal date.
* @apiSuccess {Number} userId       ID of User related to this AppClient.
*
* @apiSuccessExample Success-Response:
*HTTP/1.1 200 OK
{
  "id": 1,
  "token": "uNgZnpGeKpr8JPMM4i1WT0KuiaeSYRT7",
  "description": "Default appClient for admin",
  "createdAt": "2015-11-23T16:50:16.361Z",
  "updatedAt": "2015-11-23T16:50:16.361Z",
  "deletedAt": null,
  "userId": 1
}
*
* @apiUse defaultResponses
*/
