define({ "api": [
  {
    "type": "delete",
    "url": "/api/collectors/:id",
    "title": "5. Remove a Collector",
    "version": "1.0.0",
    "name": "DeleteCollector",
    "group": "Collectors",
    "permission": [
      {
        "name": "TokenAccess",
        "title": "The Client must have a token that allows it to get access on this resource.",
        "description": ""
      }
    ],
    "description": "<p>Collector are responsible for read RFID records from antennas and pass it to the server. Use this URI to remove a collector from database.</p> ",
    "parameter": {
      "fields": {
        "Param": [
          {
            "group": "Param",
            "type": "<p>Number</p> ",
            "optional": false,
            "field": "id",
            "description": "<p>ID of the collector.</p> "
          }
        ]
      }
    },
    "success": {
      "examples": [
        {
          "title": "Success-Response:",
          "content": "HTTP/1.1 200 OK\n  {\n    \"id\": 1,\n    \"name\": \"Collector updated\",\n    \"lat\": \"-25.436014\",\n    \"lng\": \"-54.597145\",\n    \"mac\": \"78:2b:cb:c0:75:24\",\n    \"description\": \"Collector description updated\",\n    \"createdAt\": \"2015-11-23T16:50:22.064Z\",\n    \"updatedAt\": \"2015-11-27T15:32:18.064Z\",\n    \"deletedAt\": \"2015-11-27T17:55:12.910Z\",\n    \"groupId\": 1,\n    \"status\": \"OFFLINE\"\n  }",
          "type": "json"
        }
      ]
    },
    "filename": "apidoc_source/collectors/deleteCollector.js",
    "groupTitle": "Collectors",
    "error": {
      "fields": {
        "Error 4xx": [
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "Unauthorized",
            "description": "<p>Missing Authorization headers or the given token do not exist. The client is Unauthorized and can't use the API.</p> "
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "Forbidden",
            "description": "<p>The client is authenticated but has not authorization on the requested resource.</p> "
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "NotFound",
            "description": "<p>The required resource does not exist.</p> "
          }
        ]
      },
      "examples": [
        {
          "title": "UnauthorizedError:",
          "content": "HTTP/1.1 401 Unauthorized\n\t\"Unauthorized\"",
          "type": "json"
        },
        {
          "title": "ForbiddenError:",
          "content": "HTTP/1.1 403 Forbidden\n{\n  \"message\": \"Token not allowed for this opperation\",\n  \"status\": 403,\n  \"error\": \"Get out dog.\"\n}",
          "type": "json"
        },
        {
          "title": "ResponseError:",
          "content": "HTTP/1.1 'Code & Message'\n{\n \"message\": \"Any Message here\",\n \"status\": 'code',\n \"error\": \"Detailed error here\"\n}",
          "type": "json"
        }
      ]
    }
  },
  {
    "type": "get",
    "url": "/api/collectors",
    "title": "1. Get array of Collectors",
    "version": "1.0.0",
    "name": "GetCollectors",
    "group": "Collectors",
    "permission": [
      {
        "name": "TokenAccess",
        "title": "The Client must have a token that allows it to get access on this resource.",
        "description": ""
      }
    ],
    "description": "<p>Collector are responsible for read RFID records from antennas and pass it to the server. Use this URI to search on platform for Collectors that match the given query or all the availables collectors.</p> ",
    "examples": [
      {
        "title": "Example usage:",
        "content": "curl -i https://localhost/api/collectors",
        "type": "json"
      },
      {
        "title": "Query Example:",
        "content": "curl -i https://localhost/api/collectors?q={\"limit\": 3}",
        "type": "json"
      }
    ],
    "success": {
      "fields": {
        "Success 200": [
          {
            "group": "Success 200",
            "type": "<p>Object[]</p> ",
            "optional": false,
            "field": "collector",
            "description": "<p>List of Collectors.</p> "
          }
        ]
      },
      "examples": [
        {
          "title": "Success-Response:",
          "content": "HTTP/1.1 200 OK\n[\n  {\n    \"id\": 1,\n    \"name\": \"Collector-Simulator1\",\n    \"lat\": \"-25.436014\",\n    \"lng\": \"-54.597145\",\n    \"mac\": \"78:2b:cb:c0:75:24\",\n    \"description\": \"Collector generated by Collector-Simulator\",\n    \"createdAt\": \"2015-11-23T16:50:22.064Z\",\n    \"updatedAt\": \"2015-11-23T16:50:22.064Z\",\n    \"deletedAt\": null,\n    \"groupId\": 1,\n    \"status\": \"OFFLINE\"\n  },\n  {\n    \"id\": 2,\n    \"name\": \"Collector-Simulator2\",\n    \"lat\": \"-25.436014\",\n    \"lng\": \"-54.597145\",\n    \"mac\": \"78:2b:cb:c0:75:86\",\n    \"description\": \"Collector generated by Collector-Simulator\",\n    \"createdAt\": \"2015-11-23T16:50:22.066Z\",\n    \"updatedAt\": \"2015-11-23T16:50:22.066Z\",\n    \"deletedAt\": null,\n    \"groupId\": 1,\n    \"status\": \"ONLINE\"\n  }\n]",
          "type": "json"
        }
      ]
    },
    "filename": "apidoc_source/collectors/getAll.js",
    "groupTitle": "Collectors",
    "parameter": {
      "fields": {
        "Parameter": [
          {
            "group": "Parameter",
            "optional": false,
            "field": "q",
            "description": "<p>(Query) Received all parameter defined by Sequelize documentations. Available <a href=\"http://docs.sequelizejs.com/en/latest/docs/querying/\" target=\"_blank\"> here.</a></p> "
          }
        ]
      }
    },
    "error": {
      "fields": {
        "Error 4xx": [
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "Unauthorized",
            "description": "<p>Missing Authorization headers or the given token do not exist. The client is Unauthorized and can't use the API.</p> "
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "Forbidden",
            "description": "<p>The client is authenticated but has not authorization on the requested resource.</p> "
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "NotFound",
            "description": "<p>The required resource does not exist.</p> "
          }
        ]
      },
      "examples": [
        {
          "title": "UnauthorizedError:",
          "content": "HTTP/1.1 401 Unauthorized\n\t\"Unauthorized\"",
          "type": "json"
        },
        {
          "title": "ForbiddenError:",
          "content": "HTTP/1.1 403 Forbidden\n{\n  \"message\": \"Token not allowed for this opperation\",\n  \"status\": 403,\n  \"error\": \"Get out dog.\"\n}",
          "type": "json"
        },
        {
          "title": "ResponseError:",
          "content": "HTTP/1.1 'Code & Message'\n{\n \"message\": \"Any Message here\",\n \"status\": 'code',\n \"error\": \"Detailed error here\"\n}",
          "type": "json"
        }
      ]
    }
  },
  {
    "type": "get",
    "url": "/api/collectors/:id",
    "title": "2. Get only one Collector",
    "version": "1.0.0",
    "name": "GetOneCollector",
    "group": "Collectors",
    "permission": [
      {
        "name": "TokenAccess",
        "title": "The Client must have a token that allows it to get access on this resource.",
        "description": ""
      }
    ],
    "description": "<p>Collector are responsible for read RFID records from antennas and pass it to the server. Use this URI to search on platform for one Collector that match the given ID.</p> ",
    "parameter": {
      "fields": {
        "Param": [
          {
            "group": "Param",
            "type": "<p>Number</p> ",
            "optional": false,
            "field": "id",
            "description": "<p>ID of the collector.</p> "
          }
        ]
      }
    },
    "success": {
      "fields": {
        "Success 200": [
          {
            "group": "Success 200",
            "type": "<p>Number</p> ",
            "optional": false,
            "field": "Id",
            "description": "<p>Collector ID on database.</p> "
          },
          {
            "group": "Success 200",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "name",
            "description": "<p>Name of the collector.</p> "
          },
          {
            "group": "Success 200",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "lat",
            "description": "<p>Coordinate of the collector.</p> "
          },
          {
            "group": "Success 200",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "lng",
            "description": "<p>Coordinate of the collector.</p> "
          },
          {
            "group": "Success 200",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "mac",
            "description": "<p>Macaddrass from the collector's hardware.</p> "
          },
          {
            "group": "Success 200",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "description",
            "description": "<p>Defines the collector.</p> "
          },
          {
            "group": "Success 200",
            "type": "<p>Date</p> ",
            "optional": false,
            "field": "createdAt",
            "description": "<p>Creation date generated by Sequelize.</p> "
          },
          {
            "group": "Success 200",
            "type": "<p>Date</p> ",
            "optional": false,
            "field": "updatedAt",
            "description": "<p>Last update of this collector.</p> "
          },
          {
            "group": "Success 200",
            "type": "<p>Date</p> ",
            "optional": false,
            "field": "deletedAt",
            "description": "<p>Null if collector is not deleted or removal date.</p> "
          },
          {
            "group": "Success 200",
            "type": "<p>Number</p> ",
            "optional": false,
            "field": "groupId",
            "description": "<p>ID of related group.</p> "
          },
          {
            "group": "Success 200",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "status",
            "description": "<p>Status ONLINE or OFFLINE.</p> "
          }
        ]
      },
      "examples": [
        {
          "title": "Success-Response:",
          "content": "HTTP/1.1 200 OK\n  {\n    \"id\": 1,\n    \"name\": \"Collector-Simulator1\",\n    \"lat\": \"-25.436014\",\n    \"lng\": \"-54.597145\",\n    \"mac\": \"78:2b:cb:c0:75:24\",\n    \"description\": \"Collector generated by Collector-Simulator\",\n    \"createdAt\": \"2015-11-23T16:50:22.064Z\",\n    \"updatedAt\": \"2015-11-23T16:50:22.064Z\",\n    \"deletedAt\": null,\n    \"groupId\": 1,\n    \"status\": \"ONLINE\"\n  }",
          "type": "json"
        }
      ]
    },
    "filename": "apidoc_source/collectors/getOne.js",
    "groupTitle": "Collectors",
    "error": {
      "fields": {
        "Error 4xx": [
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "Unauthorized",
            "description": "<p>Missing Authorization headers or the given token do not exist. The client is Unauthorized and can't use the API.</p> "
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "Forbidden",
            "description": "<p>The client is authenticated but has not authorization on the requested resource.</p> "
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "NotFound",
            "description": "<p>The required resource does not exist.</p> "
          }
        ]
      },
      "examples": [
        {
          "title": "UnauthorizedError:",
          "content": "HTTP/1.1 401 Unauthorized\n\t\"Unauthorized\"",
          "type": "json"
        },
        {
          "title": "ForbiddenError:",
          "content": "HTTP/1.1 403 Forbidden\n{\n  \"message\": \"Token not allowed for this opperation\",\n  \"status\": 403,\n  \"error\": \"Get out dog.\"\n}",
          "type": "json"
        },
        {
          "title": "ResponseError:",
          "content": "HTTP/1.1 'Code & Message'\n{\n \"message\": \"Any Message here\",\n \"status\": 'code',\n \"error\": \"Detailed error here\"\n}",
          "type": "json"
        }
      ]
    }
  },
  {
    "type": "post",
    "url": "/api/collectors",
    "title": "3. Create a new Collector",
    "version": "1.0.0",
    "name": "PostCollector",
    "group": "Collectors",
    "permission": [
      {
        "name": "TokenAccess",
        "title": "The Client must have a token that allows it to get access on this resource.",
        "description": ""
      }
    ],
    "description": "<p>Collector are responsible for read RFID records from antennas and pass it to the server. Use this URI to insert a new collector.</p> ",
    "examples": [
      {
        "title": "Object Example:",
        "content": "{\n  \"name\": \"Collector-Simulator1\",\n  \"lat\": \"-25.436014\",\n  \"lng\": \"-54.597145\",\n  \"mac\": \"78:2b:cb:c0:75:24\",\n  \"description\": \"Collector generated by Collector-Simulator\",\n  \"groupId\": 1\n}",
        "type": "json"
      }
    ],
    "parameter": {
      "fields": {
        "Body": [
          {
            "group": "Body",
            "type": "<p>Number</p> ",
            "optional": false,
            "field": "groupId",
            "description": "<p>Group ID the collector is related {Required}.</p> "
          },
          {
            "group": "Body",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "name",
            "description": "<p>Name of the Collector {Required, Unique}.</p> "
          },
          {
            "group": "Body",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "lat",
            "description": "<p>Geolocation of the Collector - Latitude.</p> "
          },
          {
            "group": "Body",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "lng",
            "description": "<p>Geolocation of the Collector - Longitude.</p> "
          },
          {
            "group": "Body",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "mac",
            "description": "<p>MAC address of the Collector {Required, Unique}.</p> "
          },
          {
            "group": "Body",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "description",
            "description": "<p>Brief description to describe the Collector.</p> "
          }
        ]
      }
    },
    "success": {
      "examples": [
        {
          "title": "Success-Response:",
          "content": "HTTP/1.1 200 OK\n  {\n    \"id\": 1,\n    \"name\": \"Collector-Simulator1\",\n    \"lat\": \"-25.436014\",\n    \"lng\": \"-54.597145\",\n    \"mac\": \"78:2b:cb:c0:75:24\",\n    \"description\": \"Collector generated by Collector-Simulator\",\n    \"createdAt\": \"2015-11-23T16:50:22.064Z\",\n    \"updatedAt\": \"2015-11-23T16:50:22.064Z\",\n    \"deletedAt\": null,\n    \"groupId\": 1,\n    \"status\": \"OFFLINE\"\n  }",
          "type": "json"
        }
      ]
    },
    "filename": "apidoc_source/collectors/newCollector.js",
    "groupTitle": "Collectors",
    "error": {
      "fields": {
        "Error 4xx": [
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "Unauthorized",
            "description": "<p>Missing Authorization headers or the given token do not exist. The client is Unauthorized and can't use the API.</p> "
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "Forbidden",
            "description": "<p>The client is authenticated but has not authorization on the requested resource.</p> "
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "NotFound",
            "description": "<p>The required resource does not exist.</p> "
          }
        ]
      },
      "examples": [
        {
          "title": "UnauthorizedError:",
          "content": "HTTP/1.1 401 Unauthorized\n\t\"Unauthorized\"",
          "type": "json"
        },
        {
          "title": "ForbiddenError:",
          "content": "HTTP/1.1 403 Forbidden\n{\n  \"message\": \"Token not allowed for this opperation\",\n  \"status\": 403,\n  \"error\": \"Get out dog.\"\n}",
          "type": "json"
        },
        {
          "title": "ResponseError:",
          "content": "HTTP/1.1 'Code & Message'\n{\n \"message\": \"Any Message here\",\n \"status\": 'code',\n \"error\": \"Detailed error here\"\n}",
          "type": "json"
        }
      ]
    }
  },
  {
    "type": "put",
    "url": "/api/collectors/:id",
    "title": "4. Update an existing Collector",
    "version": "1.0.0",
    "name": "PutCollector",
    "group": "Collectors",
    "permission": [
      {
        "name": "TokenAccess",
        "title": "The Client must have a token that allows it to get access on this resource.",
        "description": ""
      }
    ],
    "description": "<p>Collector are responsible for read RFID records from antennas and pass it to the server. Use this URI to update a collector from database.</p> ",
    "parameter": {
      "fields": {
        "Param": [
          {
            "group": "Param",
            "type": "<p>Number</p> ",
            "optional": false,
            "field": "id",
            "description": "<p>ID of the collector.</p> "
          }
        ],
        "Body": [
          {
            "group": "Body",
            "type": "<p>Number</p> ",
            "optional": false,
            "field": "groupId",
            "description": "<p>Group ID the collector is related {Required}.</p> "
          },
          {
            "group": "Body",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "name",
            "description": "<p>Name of the Collector {Required, Unique}.</p> "
          },
          {
            "group": "Body",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "lat",
            "description": "<p>Geolocation of the Collector - Latitude.</p> "
          },
          {
            "group": "Body",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "lng",
            "description": "<p>Geolocation of the Collector - Longitude.</p> "
          },
          {
            "group": "Body",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "mac",
            "description": "<p>MAC address of the Collector {Required, Unique}.</p> "
          },
          {
            "group": "Body",
            "type": "<p>String</p> ",
            "optional": false,
            "field": "description",
            "description": "<p>Brief description to describe the Collector.</p> "
          }
        ]
      }
    },
    "examples": [
      {
        "title": "Object Example:",
        "content": "{\n  \"id\": 1,\n  \"name\": \"Collector updated\",\n  \"lat\": \"-25.436014\",\n  \"lng\": \"-54.597145\",\n  \"mac\": \"78:2b:cb:c0:75:24\",\n  \"description\": \"Collector description updated\",\n  \"createdAt\": \"2015-11-23T16:50:22.064Z\",\n  \"updatedAt\": \"2015-11-23T16:50:22.064Z\",\n  \"deletedAt\": null,\n  \"groupId\": 1,\n}",
        "type": "json"
      }
    ],
    "success": {
      "examples": [
        {
          "title": "Success-Response:",
          "content": "HTTP/1.1 200 OK\n  {\n    \"id\": 1,\n    \"name\": \"Collector updated\",\n    \"lat\": \"-25.436014\",\n    \"lng\": \"-54.597145\",\n    \"mac\": \"78:2b:cb:c0:75:24\",\n    \"description\": \"Collector description updated\",\n    \"createdAt\": \"2015-11-23T16:50:22.064Z\",\n    \"updatedAt\": \"2015-11-27T15:32:18.064Z\",\n    \"deletedAt\": null,\n    \"groupId\": 1,\n    \"status\": \"OFFLINE\"\n  }",
          "type": "json"
        }
      ]
    },
    "filename": "apidoc_source/collectors/updateCollector.js",
    "groupTitle": "Collectors",
    "error": {
      "fields": {
        "Error 4xx": [
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "Unauthorized",
            "description": "<p>Missing Authorization headers or the given token do not exist. The client is Unauthorized and can't use the API.</p> "
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "Forbidden",
            "description": "<p>The client is authenticated but has not authorization on the requested resource.</p> "
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "NotFound",
            "description": "<p>The required resource does not exist.</p> "
          }
        ]
      },
      "examples": [
        {
          "title": "UnauthorizedError:",
          "content": "HTTP/1.1 401 Unauthorized\n\t\"Unauthorized\"",
          "type": "json"
        },
        {
          "title": "ForbiddenError:",
          "content": "HTTP/1.1 403 Forbidden\n{\n  \"message\": \"Token not allowed for this opperation\",\n  \"status\": 403,\n  \"error\": \"Get out dog.\"\n}",
          "type": "json"
        },
        {
          "title": "ResponseError:",
          "content": "HTTP/1.1 'Code & Message'\n{\n \"message\": \"Any Message here\",\n \"status\": 'code',\n \"error\": \"Detailed error here\"\n}",
          "type": "json"
        }
      ]
    }
  }
] });