/**
* @api {get} /api/groups/:id 2. Get only one Group
* @apiVersion 1.0.0
* @apiName GetOneGroup
* @apiGroup Groups
* @apiPermission TokenAccess
*
* @apiDescription Group of collectors. May be grouped by institutions, places, types of collectors, etc.
* To get one group using its ID, use this route.
*
* @apiParam (Param) {Number} id ID of the group.
*
* @apiSuccess {Number} Id       Group ID on database.
* @apiSuccess {String} name       Name of the group.
* @apiSuccess {String} description       Defines the group.
* @apiSuccess {Date} createdAt       Creation date generated by Sequelize.
* @apiSuccess {Date} updatedAt       Last update of this group.
* @apiSuccess {Date} deletedAt       Null if group is not deleted or removal date.
* @apiSuccess {Boolean} isDefault       True for Group default or Null.
*
*
* @apiSuccessExample Success-Response:
*HTTP/1.1 200 OK
*   {
*     "id": 1,
*     "name": "Default Group",
*     "description": "Auto-generated Default Group",
*     "createdAt": "2015-11-23T16:50:22.064Z",
*     "updatedAt": "2015-11-23T16:50:22.064Z",
*     "deletedAt": null,
*     "isDefault": true
*   }
*
* @apiUse defaultResponses
*/
