/**
* @api {get} /api/collectors/:id 2. Get only one Collector
* @apiVersion 1.0.0
* @apiName GetOneCollector
* @apiGroup Collectors
* @apiPermission TokenAccess
*
* @apiDescription Collector are responsible for read RFID records from antennas and pass it to the server.
* Use this URI to search on platform for one Collector that match the given ID.
*
* @apiParam (Param) {Number} id ID of the collector.
*
* @apiSuccess {Number} Id       Collector ID on database.
* @apiSuccess {String} name       Name of the collector.
* @apiSuccess {String} lat       Coordinate of the collector.
* @apiSuccess {String} lng       Coordinate of the collector.
* @apiSuccess {String} mac       Macaddrass from the collector's hardware.
* @apiSuccess {String} description       Defines the collector.
* @apiSuccess {Date} createdAt       Creation date generated by Sequelize.
* @apiSuccess {Date} updatedAt       Last update of this collector.
* @apiSuccess {Date} deletedAt       Null if collector is not deleted or removal date.
* @apiSuccess {Number} groupId       ID of related group.
* @apiSuccess {String} status       Status ONLINE or OFFLINE.
* @apiSuccess {Object} records       Information about records readed from the past year, until now
*
*
* @apiSuccessExample Success-Response:
*HTTP/1.1 200 OK
*   {
*     "id": 1,
*     "name": "Collector-Simulator1",
*     "lat": "-25.436014",
*     "lng": "-54.597145",
*     "mac": "78:2b:cb:c0:75:24",
*     "description": "Collector generated by Collector-Simulator",
*     "createdAt": "2015-11-23T16:50:22.064Z",
*     "updatedAt": "2015-11-23T16:50:22.064Z",
*     "deletedAt": null,
*     "groupId": 1,
*     "status": "ONLINE",
*     "records": {
*       "year": 98,
*       "month": 98,
*       "week": 98,
*       "daily": 98,
*       "total": 98
*     }
*   }
*
* @apiUse defaultResponses
*/
