/**
* @api {post} /api/collectors 3. Create a new Collector
* @apiVersion 1.0.0
* @apiName PostCollector
* @apiGroup Collectors
* @apiPermission TokenAccess
*
* @apiDescription Collector are responsible for read RFID records from antennas and pass it to the server.
* Use this URI to insert a new collector.
*
* @apiExample Object Example:
*   {
*     "name": "Collector-Simulator1",
*     "lat": "-25.436014",
*     "lng": "-54.597145",
*     "mac": "78:2b:cb:c0:75:24",
*     "description": "Collector generated by Collector-Simulator",
*     "groupId": 1
*   }
*
* @apiParam (Body) {Number} groupId Group ID the collector is related {Required}.
* @apiParam (Body) {String} name Name of the Collector {Required, Unique}.
* @apiParam (Body) {String} lat   Geolocation of the Collector - Latitude.
* @apiParam (Body) {String} lng   Geolocation of the Collector - Longitude.
* @apiParam (Body) {String} mac MAC address of the Collector {Required, Unique}.
* @apiParam (Body) {String} description   Brief description to describe the Collector.
*
* @apiSuccessExample Success-Response:
* HTTP/1.1 200 OK
*   {
*     "id": 1,
*     "name": "Collector-Simulator1",
*     "lat": "-25.436014",
*     "lng": "-54.597145",
*     "mac": "78:2b:cb:c0:75:24",
*     "description": "Collector generated by Collector-Simulator",
*     "createdAt": "2015-11-23T16:50:22.064Z",
*     "updatedAt": "2015-11-23T16:50:22.064Z",
*     "deletedAt": null,
*     "groupId": 1,
*     "status": "OFFLINE"
*   }
*
* @apiUse defaultResponses
*/
